# .goreleaser.yml
# Build customization
builds:
  - main:
      - cmd/tffmtmd/cli.go
      - cmd/tffmtmd/main.go
    binary: tffmtmd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
