name: dockle-trivy-test

on:
  pull_request:
    branches: [ master ]
env:
  AWS_REGION: ap-northeast-1
jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
  dockle:
    name: dockle
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.0'
      - name: Check image with dockle
        run: |
          git pull https://github.com/fukubaka0825/dockle.git
          go run cmd/dockle/main.go -f sarif -o dockle-results.sarif nginx
        env:
          IMAGE_NAME: app
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'dockle-results.sarif'